### ISSUE TITLE
Adjust the rose logo so that it sits center in the nav bar

### ISSUE THREAD

**Issue by katrinasperry** [codeforpdx/website#30]
Blocked by #28 

Create PR that merges to nav_bar-redesign branch

![image](https://user-images.githubusercontent.com/29134018/142093854-c6b7c4e2-56f4-4d5f-b7f6-f55aa63e9614.png)

The navbar html can be found here: `_includes/header.html`

**Comment by kgottfri** [comment]
Should the logo align horizontally as well or is this issue just fixing the vertical alignment from increasing the size of the nav-bar?

**Comment by katrinasperry** [comment]
@kgottfri good question, this is just about fixing the vertical alignment. Thanks for asking!
