### ISSUE TITLE
Adjust "Our Partners" list to display as shown

### ISSUE THREAD

**Issue by katrinasperry** [codeforpdx/website#40]
Create PR that merges to partner_list-redesign branch 

![image](https://user-images.githubusercontent.com/29134018/142133826-b8f04bed-74d2-4493-8c60-2fa2f8e73241.png)

NOTE: all partner logos are already on the current site - keep them as is!

The partners html file can be found in: `sections/partners.html`
The `_partners` directory has all the md files <- probably don't need to modify that unless we're adding/removing partners.

**Comment by curtisbarnard** [comment]
Once I get the sponsor list updates approved and merged I'll update these cards. @katrinasperry a few design questions:

1. Do you want the aspect ratio of the cards the same from mobile up to desktop?
2. Do you want to maintain the current aspect ratio or use the updated aspect ratio from Figma:
   - Current Aspect ratio 2.14:
     - ![image](https://user-images.githubusercontent.com/100104319/160679506-ea236bd9-3a3f-45ec-82fe-04be5e09eba1.png)
   - Updated aspect ratio 2.31:
     - ![image](https://user-images.githubusercontent.com/100104319/160679947-79721877-d0c9-4b6c-8013-2e1ff3e64448.png)
3. Confirm that I am removing the box shadow?

Thanks!

**Comment by katrinasperry** [comment]
I really don't have strong feelings about aspect ratios 😂 so if you have other ideas, please share! Here's my best guess:

1. Yes, let's keep the same aspect ratio across desktop and mobile views.
2. Let's maintain the current aspect ratio.
3. Yes to removing the box shadow!

Thanks so much!

**Comment by curtisbarnard** [comment]
This is being taken care of on #70 , currently having some issues with getting the desktop layout to align correctly. See PR for more info.

![container](https://user-images.githubusercontent.com/100104319/161476009-273b0fea-56f7-4273-bd94-d1d73104ca14.JPG)
