### ISSUE TITLE
Update site global CSS standards

### ISSUE THREAD

**Issue by kgottfri** [codeforpdx/website#57]
Updating standards in main.scss to match the design of the figma mockup.  Allows for alternating section colors, decreased margins on whole site, and other minor changes.

Margin width should be updated in each section individually to 80%.  

No updates yet to global font style and size, open to suggestions if it needs to change.

Please leave comments about other global CSS standards we can update here so we don't have to individually make different changes.

**Comment by curtisbarnard** [comment]
We could add the section_header.html typography changes to this. Alternatively I think it would be good to split it out as a separate issue that someone can completely quickly. I think it might be a good first issue for someone new perhaps?
