### ISSUE TITLE
Donate button visible only on mobile

### ISSUE THREAD

**Issue by kgottfri** [codeforpdx/website#61]
Create a PR that merges into donate_button.

Update the styling of the donate button and make it visible only on mobile (screen size smaller than 549px).
Donate button shouldn't be visible on desktop.

Html can be found in includes/donate_button.html.  

<img width="609" alt="Screen Shot 2022-03-26 at 10 27 30 AM" src="https://user-images.githubusercontent.com/11969591/160250747-d5b584a3-9205-4fc1-bc78-ff0af9c6dd8f.png">

**Comment by katrinasperry** [comment]
But wait, there's an added layer of complexity: we want to keep the donate button banner on mobile.

**Comment by kgottfri** [comment]
It looks like the donate button is fixed on the bottom of the page on mobile? I was going to create a new issue for that.  If we want to keep it as is that is also fine.

Edit: it looks like it's a sticky footer.  I will make note of that, but figured that could exist in a new issue still or I could update this one to have it updated to exist only on mobile.

**Comment by katrinasperry** [comment]
Yeah this was tough to mockup on the static design, but a sticky footer sounds like the right idea! And the reasoning for this on mobile only is that we don't have room for the donate button in the mobile top nav, and we want that omnipresent donate reminder. 😉

**Comment by ghost** [comment]
Sorry about the unassigning and reassigning miscommunication between me and @kgottfri
