### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by curtisbarnard** [codeforpdx/website#66]
As it seems a lot of people are having trouble getting the repo up and running on their local machines I was wondering if we should add some additional tips to get it going. I know for my windows 10 machine I had to do the following:

- Removed `ruby "2.7.2"` from line 2 in the Gemfile
- Delete the Gemfile.lock
- run `bundle install` in the command line to regenerate a new Gemfile.lock
- run `bundle add webrick` in the command line
  - I guess this is necessary if you are running Ruby 3.0.0+ according to this site: https://jekyllrb.com/docs/

**Comment by ghost** [comment]
Hey Curtis I got this one.

**Comment by ghost** [comment]
Resolved
![image](https://user-images.githubusercontent.com/101275747/160923282-236ead1c-357f-4225-b44b-7fa622c006ff.png)

**Comment by ghost** [comment]
Jumped the gun on closing the issue.
