### ISSUE TITLE
Update status for RecordSponge

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/website#7]
The RecordSponge product status can be updated to -> 'Completed'

**Comment by yunnie** [comment]
So I cloned the repo, created a new branch, and updated the status in ./_products/record_expungement.md from "Active" to "Completed". But when I launch the site using ">sudo docker-compose up" the status still reads "Active" on the page. I'm not familiar enough with Jekyll to know what's going on.

**Comment by NickSchimek** [comment]
It probably doesn't have anything to do with Jekyll, but rather the docker configuration. I had trouble configuring the live-reload for docker (I will create a ticket for this. hopefully someone more knowledgeable can get it working). You may have to do `docker-compose down` and then `docker-compose up` to see new changes. If that still doesn't work then feel free to push up your changes. I need to make it a priority to finish the README. Feel free to update the readme with any solution you find, however don't feel like you need to view the changes before submitting this PR. Reach out to me on slack if you would like to take a look at it together.

**Comment by yunnie** [comment]
Solution is simple. Use "sudo docker-compose build" to rebuild the docker image. This will copy the updated files into the image. Then run "sudo docker-compose up" to launch the service. I'll update the readme.

**Comment by NickSchimek** [comment]
Thanks! I created issue #12 to address the docker issue.

**Comment by NickSchimek** [comment]
Fixed in issue #10
