### ISSUE TITLE
Bridge Illustration Refinement

### ISSUE THREAD

**Issue by curtisbarnard** [codeforpdx/website#89]
The current graphic is cut off and isn't showing up the same as in the figma design. Here is what is displaying on the redesign_branch:

![image](https://user-images.githubusercontent.com/100104319/163289934-c07dc18b-01d6-4a16-95d3-8484fbbd1cfd.png)

Here is what is on the figma design:

![image](https://user-images.githubusercontent.com/100104319/163290176-fd69be91-5f7b-4d02-a191-dfdc7c8debba.png)

Also in my opinion we should shift the image down to get rid of the whitespace. @katrinasperry what do you think about that? It would look something like this:

![image](https://user-images.githubusercontent.com/100104319/163290145-8064c0f4-633d-48e6-a218-13a758f24dfc.png)

**Comment by katrinasperry** [comment]
Good catch! The bridge also looks really pixel-y to me, are you seeing that too? We should have a high-res version from Alice somewhere in GitHub... I'll poke around and see if I can find it.

Let's keep the design as the designers mocked it up for now. Once we have this version live we can always do another pass of refinement!

**Comment by katrinasperry** [comment]
Got it! Let's replace the current bridge image file with this one: https://github.com/codeforpdx/website/blob/master/assets/new-site-images/stjohnbridge.png

**Comment by katrinasperry** [comment]
Just noticed that file has the bridge cut off. It looks to me like the bridge might have been cropped a bit shorter in the mockup to eliminate that cut off appearance... Do you see that too?

**Comment by curtisbarnard** [comment]
Yup I see that. Well crop it to remove that cutoff and keep the reveal at the bottom per the figma design. Thanks!
